# This is an example OpenSimH config file that shows
# the configuration line to do the port forwarding
# to the 2.11BSD TCP port 540.

set cpu 11/70 4096K fpp idle
set clk 60hz
set tto 8b

set rq ena
set rq0 rauser=1000
att rq0 gara.dsk

set tq ena
att tq0 wktcnews.tap

set dz ena
set dz lines=8
set dz vector=310
set dz 8b
att dz 9000

set xu ena
set xu type=delua
att xu nat:tcp=9023:10.0.2.4:23

# Port forward host TCP port 9540
# to 2.11BSD TCP port 540
att xu nat:tcp=9540:10.0.2.4:540

boot rq0
